import { createContext } from "react";
export const ProjectContext = createContext();

const ProjectProvider = ({ children }) => {
    //array de todos los proyectos
    const proyectos = [
        {
            id: 1,
            name: "App Web Recetapp",
            github: "https://github.com/paaolaola/proyecto-final-gary-chesi-pao",
            url: "https://magenta-pika-e54801.netlify.app",
            image: "../img/proyectos/P1/0.png",
            images: {
                image1: "../img/proyectos/P1/0.png",
                image2: "../img/proyectos/P1/1.png",
                image3: "../img/proyectos/P1/2.png",
                image4: "../img/proyectos/P1/3.png",
                image5: "../img/proyectos/P1/4.png",
                image6: "../img/proyectos/P1/5.png",
            },
            info: "Proyecto grupal y final, de Interfaz y Lógica del Bootcamp Desarrollo Frontend React, enfocado en el manejo de todos los contenidos vistos en la carrera. Incluye funcionalidades como: Filtro de búsqueda, Sorting de elementos, Validación de formularios, Rutas protegidas (sessionStorage), Creación de nuevas publicaciones, Filtro para Likes y Modificación de datos del usuario registrado/logueado. Media queries para uso responsivo.",
            skills: {
                skill1: "JavaScript",
                skill2: "React JS",
                skill3: "React Hooks",
                skill4: "Context API",
                skill5: "JSON",
                skill6: "Vite",
                skill7: "SCSS",
                skill8: "CSS Flexbox",
                skill9: "CSS Grid",
                skill10: "CSS",
                skill11: "HTML",
                skill12: "Terminal",
                skill13: "Bootstrap",
                skill14: "Media Queries",
                skill15: "Git",
                skill16: "GitHub",
            },
        },
        {
            id: 2,
            name: "App Web Pizzeria",
            github: "https://github.com/paaolaola/prueba-react-2-paola-gonzalez",
            url: "https://6577caf4ca1cbb7ce5df7dd4--superlative-wisp-3ea1f8.netlify.app/",
            image: "../img/proyectos/P2/1.png",
            images: {
                image1: "../img/proyectos/P2/0.png",
                image2: "../img/proyectos/P2/1.png",
                image3: "../img/proyectos/P2/2.png",
                image4: "../img/proyectos/P2/3.png",
                image5: "../img/proyectos/P2/4.png",
                image6: "../img/proyectos/P2/5.png",
            },
            info: "App Web de pedidos online de una pizzería que incluye catálogo, detalle del producto y carro de compras. Uso de JSON, animación con loader y Media Queries para su uso responsivo.",
            skills: {
                skill1: "JavaScript",
                skill2: "React JS",
                skill3: "React Hooks",
                skill4: "JSON",
                skill5: "Vite",
                skill6: "CSS Flexbox",
                skill7: "CSS Grid",
                skill8: "CSS",
                skill9: "HTML",
                skill10: "Terminal",
                skill11: "Media Queries",
                skill12: "Git",
                skill13: "GitHub",
                skill14: "Netlify",
            },
        },

        {
            id: 3,
            name: "CSS Grid y Responsive",
            github: "https://github.com/paaolaola/proyecto-grid-responsive",
            url: "https://paaolaola.github.io/proyecto-grid-responsive/",
            image: "../img/proyectos/P3/0.png",
            images: {
                image1: "../img/proyectos/P3/0.png",
                image2: "../img/proyectos/P3/1.png",
                image3: "../img/proyectos/P3/2.png",
            },
            info: "Proyecto básico enfocado en el manejo de CSS Grid, Flexbox y Media Queries. Diseño Responsivo",
            skills: {
                skill1: "Vite",
                skill2: "CSS Flexbox",
                skill3: "CSS Grid",
                skill4: "CSS",
                skill5: "HTML",
                skill6: "Terminal",
                skill7: "Media Queries",
                skill8: "Git",
                skill9: "GitHub",
                skill10: "GitHub Pages",
            },
        },

        {
            id: 4,
            name: "Plants Gallery Photo",
            github: "https://github.com/paaolaola/desafio-2-react-II-paola-gonzalez",
            url: "https://singular-horse-6a9d66.netlify.app/",
            image: "../img/proyectos/P4/0.png",
            images: {
                image1: "../img/proyectos/P4/0.png",
                image2: "../img/proyectos/P4/1.png",
                image3: "../img/proyectos/P4/2.png",
                image4: "../img/proyectos/P4/3.png",
            },
            info: "Proyecto destinado a una galería en línea de fotos con temática de plantas, del conocido banco de fotos de la plataforma Pexels.com usando su API privada (API KEY). Incluye sistema de likes para el usuario. Se utilizó Context API y React Router.",
            skills: {
                skill1: "JavaScript",
                skill2: "React JS",
                skill3: "React Hooks",
                skill4: "API REST",
                skill5: "JSON",
                skill6: "Vite",
                skill7: "CSS Flexbox",
                skill8: "CSS",
                skill9: "HTML",
                skill10: "Terminal",
                skill11: "Media Queries",
                skill12: "Git",
                skill13: "GitHub",
                skill14: "Netlify",
            },
        },
        {
            id: 5,
            name: "Selector Pokemon",
            github: "https://github.com/paaolaola/desafio-3-react-II-paola-gonzalez",
            url: "https://main--dapper-paletas-4e3401.netlify.app/",
            image: "../img/proyectos/P5/0.png",
            images: {
                image1: "../img/proyectos/P5/0.png",
                image2: "../img/proyectos/P5/1.png",
                image3: "../img/proyectos/P5/2.png",
            },
            info: "App Web que incluye selector de búsqueda y detalle de las características de los primeros 151 pokemon originales trayendo datos desde la pokeapi.co. Se usó React Router, React Hooks, Context API.",
            skills: {
                skill1: "JavaScript",
                skill2: "React JS",
                skill3: "React Hooks",
                skill4: "API REST",
                skill5: "Context API",
                skill6: "Vite",
                skill8: "CSS",
                skill9: "HTML",
                skill10: "Terminal",
                skill11: "Media Queries",
                skill12: "Git",
                skill13: "GitHub",
                skill14: "Netlify",
            },
        },
        {
            id: 6,
            name: "Feriados en Chile",
            github: "https://github.com/paaolaola/prueba-react-1-paola-gonzalez",
            url: "https://unique-biscuit-c647be.netlify.app/",
            image: "../img/proyectos/P6/1.png",
            images: {
                image1: "../img/proyectos/P6/0.png",
                image2: "../img/proyectos/P6/1.png",
                image3: "../img/proyectos/P6/2.png",
            },
            info: "Proyecto que se enfoca en ofrecer al usuario la búsqueda de Feriados Legales en Chile usando una API pública. Incluye tabla de datos, buscador y sorting de los elementos para una mejor visualización. Diseño responsive.",
            skills: {
                skill1: "JavaScript",
                skill2: "API REST",
                skill3: "JSON",
                skill4: "Vite",
                skill5: "CSS",
                skill6: "HTML",
                skill7: "Terminal",
                skill8: "Bootstrap",
                skill9: "Media Queries",
                skill10: "Git",
                skill11: "GitHub",
            },
        },
        {
            id: 7,
            name: "Conversor de Monedas",
            github: "https://github.com/paaolaola/prueba-js-paola-gonzalez",
            url: "https://paaolaola.github.io/prueba-js-paola-gonzalez/",
            image: "../img/proyectos/P7/1.png",
            images: {
                image1: "../img/proyectos/P7/0.png",
                image2: "../img/proyectos/P7/1.png",
                image3: "../img/proyectos/P7/2.png",
            },
            info: "Sitio web que ofrece un conversor de monedas desde peso Chileno a Dolar o Euro, el cual tiene datos actuales de la API pública mindicador.cl. Además se agrega un gráfico proveniente del plugin Chart Js de Javascript que muestra un historial de los últimos 10 días del valor de la moneda a convertir seleccionada.",
            skills: {
                skill1: "JavaScript",
                skill2: "API REST",
                skill3: "Vite",
                skill4: "CSS",
                skill5: "HTML",
                skill6: "Terminal",
                skill7: "Bootstrap",
                skill8: "Git",
                skill9: "GitHub",
                skill10: "GitHub Pages",
            },
        },
    ];

    return <ProjectContext.Provider value={{ proyectos }}>{children}</ProjectContext.Provider>;
};

export default ProjectProvider;
