import { createContext, useRef } from "react";
export const ProjectContext = createContext();

const ProjectProvider = ({ children }) => {
    //Constantes para definir los scroll de las secciones de la página de inicio
    const aboutRef = useRef(null);
    const projectsRef = useRef(null);
    const studiesRef = useRef(null);

    //Array de los proyectos actualizados
    //Se puede agregar o quitar proyectos de la lista para que se muestren en la sección de proyectos y en la página de proyectos
    const proyectos = [
        {
            id: 0,
            name: "Edunova",
            routename: "edunova",
            github: "https://github.com/LuisVera1/c18-06-m-node-react",
            url: "https://c18-06-m-node-react.vercel.app",
            image: "../img/proyectos/P0/0.png",
            video: "https://www.loom.com/embed/2ff6d64e691143f18a974f7d8599615f?sid=395acff7-9db9-402d-89c9-d6d90b4603d1",
            images: {
                image1: "../img/proyectos/P0/0.png",
                image2: "../img/proyectos/P0/1.png",
                image3: "../img/proyectos/P0/2.png",
                image4: "../img/proyectos/P0/3.png",
                image5: "../img/proyectos/P0/4.png",
                image6: "../img/proyectos/P0/5.png",
                image7: "../img/proyectos/P0/6.png",
                image8: "../img/proyectos/P0/7.png",
                image9: "../img/proyectos/P0/8.png",
                image10: "../img/proyectos/P0/9.png",
            },
            info: "Proyecto grupal realizado en los meses de simulación laboral en No Country, con la colaboración de Diseñadores UX/UI, Desarrolladores Frontend y Backend. Creación de MPV bajo la metodología Kanban. Edunova es una plataforma edTech pensada para una institución en particular que integra un sistema de matriculación online y fácil contacto con su área administrativa. En estos meses el proyecto se enfocó en el rol de administrador como usuario. En la parte frontend se usó React js, Next js, Typescript y Tailwind CSS y en la parte backend, Node, PostgreSQL, Prisma, Insomnia y JWT. Diseño prototipado a través de Figma",
            skills: {
                skill1: "React JS",
                skill2: "Next JS",
                skill3: "Typescript",
                skill4: "Tailwind CSS",
                skill10: "PrimeReact",
                skill6: "Node JS",
                skill7: "Prisma",
                skill8: "Insomnia",
                skill9: "PostgreSQL",
                skill10: "JWT",
                skill11: "GIT",
                skill12: "GitHub",
                skill13: "Vercel",
                skill14: "Yarn",
                skill15: "FIGMA",
                skill16: "Trello",
            },
        },
        {
            id: 1,
            name: "Clínica Dental RIE",
            routename: "rie-clinica-dental",
            github: "https://github.com/paaolaola/rie-project",
            url: "https://rieclinicadental.netlify.app/",
            image: "../img/proyectos/P1/0.png",
            video: "https://www.loom.com/embed/84cf9762bdd84696b0ca869bd2f213d5?sid=40a79caa-98c5-4cde-b3a6-c4c6af3a82a5",
            images: {
                image1: "../img/proyectos/P1/1.png",
                image2: "../img/proyectos/P1/0.png",
                image3: "../img/proyectos/P1/2.png",
                image4: "../img/proyectos/P1/3.png",
                image5: "../img/proyectos/P1/4.png",
                image6: "../img/proyectos/P1/5.png",
            },
            info: "Proyecto individual creado en el curso de Javascript dictado por Coderhouse de una página web que ofrece servicios dentales donde el usuario puede comprar online ingresando a través del usuario y contraseña. Enfocado en el uso de Javascript puro y manejo de funciones, arrays, objetos, métodos y ciclos. Manejo del DOM y JSON. Promesas y funciones asíncronas. Uso de AJAX y Fetch. Implementación de librerías como Bootstrap, Sweetalert y Toastify. Uso de LocalStorage para el registro, inicio de sesión y servicios guardados. Diseño responsivo.",
            skills: {
                skill1: "JavaScript",
                skill2: "DOM",
                skill3: "JSON",
                skill4: "AJAX",
                skill5: "Fetch",
                skill6: "LocalStorage",
                skill7: "Bootstrap",
                skill8: "Toastify",
                skill9: "SweetAlert",
                skill10: "Git",
                skill11: "GitHub",
                skill12: "GitHub Pages",
            },
        },
        {
            id: 2,
            name: "Recetapp",
            routename: "recetapp",
            github: "https://github.com/paaolaola/proyecto-final-gary-chesi-pao",
            url: "https://recetappweb.netlify.app/",
            image: "../img/proyectos/P2/0.png",
            video: "https://www.loom.com/embed/c511343f8094482698bba894ba8f3a0e?sid=6aad3db6-cf9c-4d7d-8c77-409270f01d23",
            images: {
                image1: "../img/proyectos/P2/0.png",
                image2: "../img/proyectos/P2/1.png",
                image3: "../img/proyectos/P2/2.png",
                image4: "../img/proyectos/P2/3.png",
                image5: "../img/proyectos/P2/4.png",
                image6: "../img/proyectos/P2/5.png",
            },
            info: "Proyecto grupal y final, de Interfaz y Lógica del Bootcamp Desarrollo Frontend React, enfocado en el manejo de todos los contenidos vistos en la carrera. Incluye funcionalidades como: Filtro de búsqueda, Sorting de elementos, Validación de formularios, Rutas protegidas (sessionStorage), Creación de nuevas publicaciones, Filtro para Likes y Modificación de datos del usuario registrado/logueado. Media queries para uso responsivo.",
            skills: {
                skill1: "JavaScript",
                skill2: "React JS",
                skill3: "React Hooks",
                skill4: "Context API",
                skill5: "JSON",
                skill6: "Vite",
                skill7: "SCSS",
                skill8: "CSS Flexbox",
                skill9: "CSS Grid",
                skill10: "CSS",
                skill11: "HTML",
                skill12: "Terminal",
                skill13: "Bootstrap",
                skill14: "Media Queries",
                skill15: "Git",
                skill16: "GitHub",
            },
        },
        {
            id: 3,
            name: "Mamma Mía",
            routename: "mamma-mia",
            github: "https://github.com/paaolaola/prueba-react-2-paola-gonzalez",
            url: "https://pizzeria-mammamia.netlify.app/",
            image: "../img/proyectos/P3/4.png",
            video: "https://www.loom.com/embed/e05e072f6893493b86f9bade1e8f666b?sid=30be5af6-6438-4346-b12e-fdeaa94eacac",
            images: {
                image1: "../img/proyectos/P3/0.png",
                image2: "../img/proyectos/P3/1.png",
                image3: "../img/proyectos/P3/2.png",
                image4: "../img/proyectos/P3/3.png",
                image5: "../img/proyectos/P3/4.png",
                image6: "../img/proyectos/P3/5.png",
                image7: "../img/proyectos/P3/6.png",
            },
            info: "App Web de pedidos online de una pizzería que incluye catálogo, detalle del producto y carro de compras. Uso de JSON, animación con loader y Media Queries para su uso responsivo.",
            skills: {
                skill1: "JavaScript",
                skill2: "React JS",
                skill3: "React Hooks",
                skill4: "JSON",
                skill5: "Vite",
                skill6: "CSS Flexbox",
                skill7: "CSS Grid",
                skill8: "CSS",
                skill9: "HTML",
                skill10: "Terminal",
                skill11: "Media Queries",
                skill12: "Git",
                skill13: "GitHub",
                skill14: "Netlify",
            },
        },

        // {
        //     id: 4,
        //     name: "CSS Grid y Responsive",
        //     github: "https://github.com/paaolaola/proyecto-grid-responsive",
        //     url: "https://paaolaola.github.io/proyecto-grid-responsive/",
        //     image: "../img/proyectos/P4/0.png",
        //     video: "https://www.youtube.com/embed/tFS_ooepzco?si=LJ6diyXFGijcoyWT",
        //     images: {
        //         image1: "../img/proyectos/P4/0.png",
        //         image2: "../img/proyectos/P4/1.png",
        //         image3: "../img/proyectos/P4/2.png",
        //     },
        //     info: "Proyecto básico enfocado en el manejo de CSS Grid, Flexbox y Media Queries. Diseño Responsivo",
        //     skills: {
        //         skill1: "Vite",
        //         skill2: "CSS Flexbox",
        //         skill3: "CSS Grid",
        //         skill4: "CSS",
        //         skill5: "HTML",
        //         skill6: "Terminal",
        //         skill7: "Media Queries",
        //         skill8: "Git",
        //         skill9: "GitHub",
        //         skill10: "GitHub Pages",
        //     },
        // },

        {
            id: 5,
            name: "Plants Gallery Photo",
            routename: "plants-gallery-photo",
            github: "https://github.com/paaolaola/desafio-2-react-II-paola-gonzalez",
            url: "https://plantsgalleryph.netlify.app/",
            image: "../img/proyectos/P5/2.png",
            video: "https://www.loom.com/embed/2dce119bf61f4d2f9d77d17e24df0788?sid=39541dd5-61e6-47eb-95ac-d399efcea2ca",
            images: {
                image1: "../img/proyectos/P5/0.png",
                image2: "../img/proyectos/P5/1.png",
                image3: "../img/proyectos/P5/2.png",
                image4: "../img/proyectos/P5/3.png",
                image4: "../img/proyectos/P5/4.png",
                image4: "../img/proyectos/P5/5.png",
            },
            info: "Proyecto destinado a una galería en línea de fotos con temática de plantas, del conocido banco de fotos de la plataforma Pexels.com usando su API privada (API KEY). Incluye sistema de likes para el usuario. Se utilizó Context API, React Router y React Toastify.",
            skills: {
                skill1: "JavaScript",
                skill2: "React JS",
                skill3: "React Hooks",
                skill4: "API REST",
                skill5: "JSON",
                skill6: "Vite",
                skill7: "CSS Flexbox",
                skill8: "CSS",
                skill9: "HTML",
                skill10: "Terminal",
                skill11: "Media Queries",
                skill12: "Git",
                skill13: "GitHub",
                skill14: "Netlify",
            },
        },
        {
            id: 6,
            name: "Selector Pokemon",
            routename: "selector-pokemon",
            github: "https://github.com/paaolaola/desafio-3-react-II-paola-gonzalez",
            url: "https://pokemonselector.netlify.app/",
            image: "../img/proyectos/P6/2.png",
            video: "https://www.loom.com/embed/3b983a39af314c44ae38d9bf7e9f4e90?sid=0de1df25-4a34-463b-94f2-3a3b5fc732bd",
            images: {
                image1: "../img/proyectos/P6/0.png",
                image2: "../img/proyectos/P6/1.png",
                image3: "../img/proyectos/P6/2.png",
            },
            info: "App Web que incluye un selector de búsqueda por orden alfabético y detalle de las características de los primeros 151 pokemon originales trayendo datos desde la pokeApi.co. Se usó React Router, React Hooks, Context API.",
            skills: {
                skill1: "JavaScript",
                skill2: "React JS",
                skill3: "React Hooks",
                skill4: "API REST",
                skill5: "Context API",
                skill6: "Vite",
                skill8: "CSS",
                skill9: "HTML",
                skill10: "Terminal",
                skill11: "Media Queries",
                skill12: "Git",
                skill13: "GitHub",
                skill14: "Netlify",
            },
        },
        {
            id: 7,
            name: "Feriados en Chile",
            routename: "feriados-en-chile",
            github: "https://github.com/paaolaola/prueba-react-1-paola-gonzalez",
            url: "https://feriadoschile.netlify.app/",
            image: "../img/proyectos/P7/0.png",
            video: "https://www.loom.com/embed/f6041c5b6bcc43f5bb0c30d432b23967?sid=628b3e4d-69db-4b36-81a3-60bb86c9703d",
            images: {
                image1: "../img/proyectos/P7/0.png",
                image2: "../img/proyectos/P7/1.png",
                image3: "../img/proyectos/P7/2.png",
            },
            info: "Proyecto que se enfoca en ofrecer al usuario la búsqueda de Feriados Legales en Chile usando una API pública. Incluye tabla de datos, buscador y sorting de los elementos para una mejor visualización. Diseño responsive.",
            skills: {
                skill1: "JavaScript",
                skill2: "API REST",
                skill3: "JSON",
                skill4: "Vite",
                skill5: "CSS",
                skill6: "HTML",
                skill7: "Terminal",
                skill8: "Bootstrap",
                skill9: "Media Queries",
                skill10: "Git",
                skill11: "GitHub",
            },
        },

        {
            id: 8,
            name: "Conversor de Monedas",
            routename: "conversor-de-monedas",
            github: "https://github.com/paaolaola/prueba-js-paola-gonzalez",
            url: "https://paaolaola.github.io/prueba-js-paola-gonzalez/",
            image: "../img/proyectos/P8/1.png",
            video: "https://www.loom.com/embed/82ab4c4b1e7348448ecca23709e3001a?sid=79c303a8-6267-4697-878c-286a0960d6d8",
            images: {
                image1: "../img/proyectos/P8/0.png",
                image2: "../img/proyectos/P8/1.png",
                image3: "../img/proyectos/P8/2.png",
            },
            info: "Sitio web que ofrece un conversor de monedas desde peso Chileno a Dolar o Euro, el cual tiene datos actuales de la API pública mindicador.cl. Además se agrega un gráfico proveniente del plugin Chart Js de Javascript que muestra un historial de los últimos 10 días del valor de la moneda a convertir seleccionada. Uso de Javascript puro.",
            skills: {
                skill1: "JavaScript",
                skill2: "API REST",
                skill3: "Vite",
                skill4: "CSS",
                skill5: "HTML",
                skill6: "Terminal",
                skill7: "Bootstrap",
                skill8: "Git",
                skill9: "GitHub",
                skill10: "GitHub Pages",
            },
        },
    ];

    return <ProjectContext.Provider value={{ proyectos, studiesRef, projectsRef, aboutRef }}>{children}</ProjectContext.Provider>;
};

export default ProjectProvider;
